apiVersion: v1
kind: Service
metadata:
  name: file-storage-external
spec:
  type: NodePort
  ports:
    - port: 8055
      nodePort: 30055
      targetPort: 8055
  selector:
    svc: file-storage-service