spring:
  application:
    name: file-storage-service
  jpa:
    properties:
      hibernate.jdbc.time_zone: Asia/Jakarta
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.show_sql: true
      hibernate.jdbc.batch_size: 10
      hibernate.jdbc.batch_versioned_data: true
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.jdbc.fetch_size: 50
      hibernate.criteria.literal_handling_mode: BIND
      hibernate.query.fail_on_pagination_over_collection_fetch: true
      hibernate.query.in_clause_parameter_padding: true
    hibernate:
      ddl-auto: none
    open-in-view: false
  datasource:
    hikari:
      auto-commit: false
  transaction:
    default-timeout: 10s
    rollback-on-commit-failure: true
  servlet:
    multipart:
      max-file-size: 5MB

server:
  port: 8055

application:
  security-secret: i9/50QWzeyE21WoeHtHc9uUS28+B5fOUbBZ0W8GoqtJfjVnlEkElszaZLFC/KIUBJ/4BVM2t9K9iKHNaOrUEBg==
  max-block-size: 10000 # 1KB

logging:
  level:
    org.springframework.integration.file: TRACE
    org.springframework.cache: TRACE