spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
            allowedMethods: "*"
            allowCredentials: true
        add-to-simple-url-handler-mapping: true
      routes:
        - id: partner-service
          uri: ${application.destinations.partner-service.url}
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=0
        - id: room-service
          uri: ${application.destinations.room-service.url}
          predicates:
            - Path=/api/room/**,/api/promotion/**
          filters:
            - StripPrefix=0
        - id: reservation-service
          uri: ${application.destinations.reservation-service.url}
          predicates:
            - Path=/api/reservation/**
          filters:
            - StripPrefix=0
        - id: rental-service
          uri: ${application.destinations.rental-service.url}
          predicates:
            - Path=/api/rental/**
          filters:
            - StripPrefix=0
server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway.handler.predicate: trace

application:
  security:
    secret: i7/50QWzeyE21WoeHtHc9uUS28+A5fOUbBZ0W8GoqtJfjVnlEkElszaZLFC/KIUBJ/4BVM2t9K9iKHNaOrUEBg==
  destinations:
    partner-service:
      url: http://localhost:8081
      authenticate: ${application.destinations.partner-service.url}/api/authenticate
      department-get: ${application.destinations.partner-service.url}/api/employee/department
    room-service:
      url: http://localhost:8084
      suite-type-get: ${application.destinations.room-service.url}/api/room/suite_type
      suite-style-get: ${application.destinations.room-service.url}/api/room/suite_style
    rental-service:
      url: http://localhost:8082
      service-get: ${application.destinations.rental-service.url}/api/service
    reservation-service:
      url: http://localhost:8083