spring:
  application:
    name: room-service
  datasource:
    hikari:
      auto-commit: false
    url: jdbc:postgresql://192.168.1.7:5432/hba_roomdb
    username: dell
    password: delladmin
  jpa:
    properties:
      hibernate.jdbc.time_zone: Asia/Jakarta
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.show_sql: true
      hibernate.jdbc.batch_size: 10
      hibernate.jdbc.batch_versioned_data: true
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.jdbc.fetch_size: 50
      hibernate.criteria.literal_handling_mode: BIND
      hibernate.query.fail_on_pagination_over_collection_fetch: true
      hibernate.query.in_clause_parameter_padding: true
    hibernate:
      ddl-auto: none
    open-in-view: false
  transaction:
    default-timeout: 10s
    rollback-on-commit-failure: true
  data:
    mongodb:
      host: 192.168.1.7
      port: 27017
      database: roomdb

server:
  port: 8084

logging:
  level:
    org.springframework.data.mongodb: DEBUG